function plotting(Ts, Duration, sol)
    figure
    subplot(3,2,1)
    plot(0:Ts:Duration,sol(1,:))
    xlabel('time')
    ylabel('z')
    title('cart position')
    subplot(3,2,2)
    plot(0:Ts:Duration,sol(2,:))
    xlabel('time')
    ylabel('zdot ')
    title(sprintf('cart velocity (max |v| = %.2f m/s)',max(abs(sol(2,:)))))
    subplot(3,2,3)
    plot(0:Ts:Duration,sol(3,:)/pi*180)
    xlabel('time')
    ylabel('theta [°]')
    title(sprintf('pendulum angle (max |angle| = %.2f °)',max(abs(sol(3,:)/pi*180))))
    subplot(3,2,4)
    plot(0:Ts:Duration,sol(4,:))
    xlabel('time')
    ylabel('thetadot')
    title('pendulum velocity')
    subplot(3,2,5)
    plot(0:Ts:Duration,sol(5,:))
    xlabel('time')
    ylabel('mv')
    title(sprintf('effort (max |u| = %.2f N)',max(abs(sol(5,:)))))
end